### ISSUE TITLE
Doesn't print correct logger name with kotlin-logging-js 4.0.0-beta-19

### ISSUE THREAD

**Issue by xuan-nguyen-swe** [oshai/kotlin-logging#279]
# Code
```
class MyClass {
  private val logger = KotlinLogging.logger("MyClass")
  // private val logger = KotlinLogging.logger() // same issue

  fun myFunc() {
    logger.debug { "myFunc" }
  }
}
```

# implementation("io.github.oshai:kotlin-logging-js:4.0.0-beta-19")
Output in Chrome console: `DEBUG: [DEBUG] myFunc`

# implementation("io.github.microutils:kotlin-logging-js:3.0.5")
Output in Chrome console: `DEBUG: [MyClass] myFunc`

**Comment by oshai** [comment]
Thanks for reporting, I created a test + fix in #280.

**Comment by oshai** [comment]
Fixed in 4.0.0-beta-20.

**Comment by xuan-nguyen-swe** [comment]
> Fixed in 4.0.0-beta-20.

```
class MyClass {
  private val logger1 = KotlinLogging.logger("MyClass") 
  private val logger2 = KotlinLogging.logger {}

  fun myFunc() {
    // work: DEBUG: [TemplatesDataFlow] myFunc
    logger1.debug { "myFunc" }


     // doesn't work: DEBUG: [js:1292:41)] myFunc
    logger2.debug { "myFunc" }
  }
}
```

**Comment by xuan-nguyen-swe** [comment]
My workaround

```
private fun createLogger(func: () -> Unit = {}) = KotlinLogging.logger(func)

private fun createLogger(name: String) = KotlinLogging.logger(name)

private class LoggerDelegate : ReadOnlyProperty<Any?, KLogger> {
  private lateinit var logger: KLogger

  override fun getValue(thisRef: Any?, property: KProperty<*>): KLogger {
    if (!::logger.isInitialized) {
      logger = thisRef.asDynamic()?.constructor?.name
        .unsafeCast<String?>()
        ?.let(::createLogger)
        ?: createLogger()
    }

    return logger
  }
}

fun logger(): ReadOnlyProperty<Any?, KLogger> = LoggerDelegate()
```

```
class MyClass {
  private val logger by logger()
}
```

**Comment by oshai** [comment]
The 3.0.5 impl was doing something like this:
```
KLoggerJS(func::class.js.name)
```
From what I observed this doesn't work well in all cases. So not sure it ever worked for all cases(browser/node). 
I can try what you suggested here

**Comment by oshai** [comment]
Thanks! I added the suggested code in #283

**Comment by oshai** [comment]
with `4.0.0-beta-21` it's possible to do the following in JS:
```
class MyClass {
  private val logger by KotlinLogging.logger()
}
```

**Comment by xuan-nguyen-swe** [comment]
Thanks for your very fast reply!

Handling this thing in JS is very difficult, as it's not designed for reflection and similar things we have in JVM :-).
I don't think we can handle all cases automatically.
But, we could try the best for common cases. For edge cases, devs must provide a specific name :-).

**Comment by xuan-nguyen-swe** [comment]
I have error while reloading gradle project with "4.0.0-beta-21".

`implementation("io.github.oshai:kotlin-logging:4.0.0-beta-20")` works.
`implementation("io.github.oshai:kotlin-logging:4.0.0-beta-21")` doesn't works.

```
> Task :prepareKotlinBuildScriptModel UP-TO-DATE
Failed building KotlinMPPGradleModel
org.gradle.internal.operations.BuildOperationQueueFailure: There was a failure while populating the build operation queue: Projects must be configuring
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.executeInParallel(DefaultBuildOperationExecutor.java:138)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.runAll(DefaultBuildOperationExecutor.java:102)
	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.artifact.ParallelResolveArtifactSet$VisitingSet.visit(ParallelResolveArtifactSet.java:66)
	at org.gradle.api.internal.artifacts.ivyservice.DefaultLenientConfiguration.visitArtifacts(DefaultLenientConfiguration.java:301)
	at org.gradle.api.internal.artifacts.ivyservice.DefaultLenientConfiguration.access$600(DefaultLenientConfiguration.java:75)
	at org.gradle.api.internal.artifacts.ivyservice.DefaultLenientConfiguration$3.run(DefaultLenientConfiguration.java:249)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:29)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:26)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.run(DefaultBuildOperationRunner.java:47)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:68)
	at org.gradle.api.internal.artifacts.ivyservice.DefaultLenientConfiguration.visitArtifactsWithBuildOperation(DefaultLenientConfiguration.java:246)
	at org.gradle.api.internal.artifacts.ivyservice.DefaultLenientConfiguration.access$300(DefaultLenientConfiguration.java:75)
	at org.gradle.api.internal.artifacts.ivyservice.DefaultLenientConfiguration$2.lambda$visitArtifacts$0(DefaultLenientConfiguration.java:149)
	at org.gradle.internal.work.DefaultWorkerLeaseService.runAsUnmanagedWorkerThread(DefaultWorkerLeaseService.java:121)
	at org.gradle.api.internal.artifacts.ivyservice.DefaultLenientConfiguration$2.visitArtifacts(DefaultLenientConfiguration.java:149)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$ConfigurationArtifactCollection.lambda$new$0(DefaultConfiguration.java:2093)
	at org.gradle.internal.model.CalculatedValueContainerFactory$SupplierBackedCalculator.calculateValue(CalculatedValueContainerFactory.java:81)
	at org.gradle.internal.model.CalculatedValueContainer$CalculationState.lambda$attachValue$0(CalculatedValueContainer.java:218)
	at org.gradle.internal.Try.ofFailable(Try.java:41)
	at org.gradle.internal.model.CalculatedValueContainer$CalculationState.attachValue(CalculatedValueContainer.java:213)
	at org.gradle.internal.model.CalculatedValueContainer.finalizeIfNotAlready(CalculatedValueContainer.java:186)
	at org.gradle.internal.model.CalculatedValueContainer.finalizeIfNotAlready(CalculatedValueContainer.java:177)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$ConfigurationArtifactCollection.ensureResolved(DefaultConfiguration.java:2140)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$ConfigurationArtifactCollection.getArtifacts(DefaultConfiguration.java:2112)
	at org.jetbrains.plugins.gradle.tooling.util.resolve.DependencyResolverImpl.resolveOtherFileDependencies(DependencyResolverImpl.java:428)
	at org.jetbrains.plugins.gradle.tooling.util.resolve.DependencyResolverImpl.resolveDependencies(DependencyResolverImpl.java:335)
	at org.jetbrains.plugins.gradle.tooling.util.resolve.DependencyResolverImpl.resolveDependencies(DependencyResolverImpl.java:105)
	at org.jetbrains.kotlin.idea.gradleTooling.builders.KotlinMultiplatformDependenciesBuilder.buildDependencies(KotlinMultiplatformDependenciesBuilder.kt:42)
	at org.jetbrains.kotlin.idea.gradleTooling.builders.KotlinMultiplatformDependenciesBuilder.buildComponent(KotlinMultiplatformDependenciesBuilder.kt:23)
	at org.jetbrains.kotlin.idea.gradleTooling.builders.KotlinSourceSetProtoBuilder$Companion.buildMetadataDependencies(KotlinSourceSetProtoBuilder.kt:128)
	at org.jetbrains.kotlin.idea.gradleTooling.builders.KotlinSourceSetProtoBuilder$Companion.access$buildMetadataDependencies(KotlinSourceSetProtoBuilder.kt:94)
	at org.jetbrains.kotlin.idea.gradleTooling.builders.KotlinSourceSetProtoBuilder$buildComponent$sourceSetDependenciesBuilder$1.invoke(KotlinSourceSetProtoBuilder.kt:62)
	at org.jetbrains.kotlin.idea.gradleTooling.builders.KotlinSourceSetProtoBuilder$buildComponent$sourceSetDependenciesBuilder$1.invoke(KotlinSourceSetProtoBuilder.kt:56)
	at org.jetbrains.kotlin.idea.gradleTooling.KotlinSourceSetProto.buildKotlinSourceSetImpl(KotlinMPPGradleModelImpl.kt:30)
	at org.jetbrains.kotlin.idea.gradleTooling.KotlinMPPGradleModelBuilder.buildSourceSets(KotlinMPPGradleModelBuilder.kt:124)
	at org.jetbrains.kotlin.idea.gradleTooling.KotlinMPPGradleModelBuilder.buildAll(KotlinMPPGradleModelBuilder.kt:54)
	at org.jetbrains.kotlin.idea.gradleTooling.KotlinMPPGradleModelBuilder.buildAll(KotlinMPPGradleModelBuilder.kt:36)
	at org.jetbrains.kotlin.idea.gradleTooling.KotlinMPPGradleModelBuilder.buildAll(KotlinMPPGradleModelBuilder.kt:24)
	at org.jetbrains.plugins.gradle.tooling.internal.ExtraModelBuilder.buildAll(ExtraModelBuilder.java:107)
	at org.jetbrains.plugins.gradle.tooling.internal.ExtraModelBuilder.buildAll(ExtraModelBuilder.java:76)
	at org.gradle.tooling.provider.model.internal.DefaultToolingModelBuilderRegistry$BuilderWithParameter.build(DefaultToolingModelBuilderRegistry.java:287)
	at org.gradle.tooling.provider.model.internal.DefaultToolingModelBuilderRegistry$UserCodeAssigningBuilder.lambda$build$0(DefaultToolingModelBuilderRegistry.java:374)
	at org.gradle.configuration.internal.DefaultUserCodeApplicationContext$CurrentApplication.reapply(DefaultUserCodeApplicationContext.java:109)
	at org.gradle.tooling.provider.model.internal.DefaultToolingModelBuilderRegistry$UserCodeAssigningBuilder.build(DefaultToolingModelBuilderRegistry.java:374)
	at org.gradle.tooling.provider.model.internal.DefaultToolingModelBuilderRegistry$LockSingleProjectBuilder.lambda$build$0(DefaultToolingModelBuilderRegistry.java:304)
	at org.gradle.api.internal.project.DefaultProjectStateRegistry$ProjectStateImpl.lambda$fromMutableState$1(DefaultProjectStateRegistry.java:374)
	at org.gradle.internal.work.DefaultWorkerLeaseService.withReplacedLocks(DefaultWorkerLeaseService.java:345)
	at org.gradle.api.internal.project.DefaultProjectStateRegistry$ProjectStateImpl.fromMutableState(DefaultProjectStateRegistry.java:374)
	at org.gradle.tooling.provider.model.internal.DefaultToolingModelBuilderRegistry$LockSingleProjectBuilder.build(DefaultToolingModelBuilderRegistry.java:304)
	at org.gradle.tooling.provider.model.internal.DefaultToolingModelBuilderRegistry$BuildOperationWrappingBuilder$1.call(DefaultToolingModelBuilderRegistry.java:337)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:199)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:73)
	at org.gradle.tooling.provider.model.internal.DefaultToolingModelBuilderRegistry$BuildOperationWrappingBuilder.build(DefaultToolingModelBuilderRegistry.java:334)
	at org.gradle.internal.build.DefaultBuildToolingModelController$AbstractToolingScope.getModel(DefaultBuildToolingModelController.java:82)
	at org.gradle.tooling.internal.provider.runner.DefaultBuildController.getModel(DefaultBuildController.java:106)
	at org.gradle.tooling.internal.consumer.connection.ParameterAwareBuildControllerAdapter.getModel(ParameterAwareBuildControllerAdapter.java:39)
	at org.gradle.tooling.internal.consumer.connection.UnparameterizedBuildController.getModel(UnparameterizedBuildController.java:113)
	at org.gradle.tooling.internal.consumer.connection.NestedActionAwareBuildControllerAdapter.getModel(NestedActionAwareBuildControllerAdapter.java:31)
	at org.gradle.tooling.internal.consumer.connection.UnparameterizedBuildController.findModel(UnparameterizedBuildController.java:97)
	at org.gradle.tooling.internal.consumer.connection.NestedActionAwareBuildControllerAdapter.findModel(NestedActionAwareBuildControllerAdapter.java:31)
	at org.gradle.tooling.internal.consumer.connection.UnparameterizedBuildController.findModel(UnparameterizedBuildController.java:81)
	at org.gradle.tooling.internal.consumer.connection.NestedActionAwareBuildControllerAdapter.findModel(NestedActionAwareBuildControllerAdapter.java:31)
	at org.jetbrains.plugins.gradle.model.ProjectImportAction$MyBuildController.findModel(ProjectImportAction.java:658)
	at org.jetbrains.plugins.gradle.model.ClassSetProjectImportModelProvider.populateProjectModels(ClassSetProjectImportModelProvider.java:31)
	at org.jetbrains.plugins.gradle.model.ProjectImportAction.getProjectModels(ProjectImportAction.java:338)
	at org.jetbrains.plugins.gradle.model.ProjectImportAction.access$500(ProjectImportAction.java:42)
	at org.jetbrains.plugins.gradle.model.ProjectImportAction$4.execute(ProjectImportAction.java:249)
	at org.jetbrains.plugins.gradle.model.ProjectImportAction$4.execute(ProjectImportAction.java:246)
	at org.jetbrains.plugins.gradle.model.ProjectImportAction.fetchProjectBuildModels(ProjectImportAction.java:262)
	at org.jetbrains.plugins.gradle.model.ProjectImportAction.execute(ProjectImportAction.java:137)
	at org.jetbrains.plugins.gradle.model.ProjectImportAction.execute(ProjectImportAction.java:42)
	at org.gradle.tooling.internal.consumer.connection.InternalBuildActionAdapter.execute(InternalBuildActionAdapter.java:64)
	at org.gradle.tooling.internal.provider.runner.AbstractClientProvidedBuildActionRunner$ActionAdapter.runAction(AbstractClientProvidedBuildActionRunner.java:131)
	at org.gradle.tooling.internal.provider.runner.AbstractClientProvidedBuildActionRunner$ActionAdapter.fromBuildModel(AbstractClientProvidedBuildActionRunner.java:104)
	at org.gradle.tooling.internal.provider.runner.AbstractClientProvidedBuildActionRunner$ActionAdapter.fromBuildModel(AbstractClientProvidedBuildActionRunner.java:84)
	at org.gradle.internal.buildtree.DefaultBuildTreeModelCreator.fromBuildModel(DefaultBuildTreeModelCreator.java:57)
	at org.gradle.internal.buildtree.DefaultBuildTreeLifecycleController.lambda$fromBuildModel$1(DefaultBuildTreeLifecycleController.java:82)
	at org.gradle.internal.buildtree.DefaultBuildTreeLifecycleController.lambda$runBuild$4(DefaultBuildTreeLifecycleController.java:106)
	at org.gradle.internal.model.StateTransitionController.lambda$transition$5(StateTransitionController.java:166)
	at org.gradle.internal.model.StateTransitionController.doTransition(StateTransitionController.java:247)
	at org.gradle.internal.model.StateTransitionController.lambda$transition$6(StateTransitionController.java:166)
	at org.gradle.internal.work.DefaultSynchronizer.withLock(DefaultSynchronizer.java:44)
	at org.gradle.internal.model.StateTransitionController.transition(StateTransitionController.java:166)
	at org.gradle.internal.buildtree.DefaultBuildTreeLifecycleController.runBuild(DefaultBuildTreeLifecycleController.java:103)
	at org.gradle.internal.buildtree.DefaultBuildTreeLifecycleController.fromBuildModel(DefaultBuildTreeLifecycleController.java:74)
	at org.gradle.tooling.internal.provider.runner.AbstractClientProvidedBuildActionRunner.runClientAction(AbstractClientProvidedBuildActionRunner.java:43)
	at org.gradle.tooling.internal.provider.runner.ClientProvidedPhasedActionRunner.run(ClientProvidedPhasedActionRunner.java:53)
	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
	at org.gradle.internal.buildtree.ProblemReportingBuildActionRunner.run(ProblemReportingBuildActionRunner.java:49)
	at org.gradle.launcher.exec.BuildOutcomeReportingBuildActionRunner.run(BuildOutcomeReportingBuildActionRunner.java:65)
	at org.gradle.tooling.internal.provider.FileSystemWatchingBuildActionRunner.run(FileSystemWatchingBuildActionRunner.java:136)
	at org.gradle.launcher.exec.BuildCompletionNotifyingBuildActionRunner.run(BuildCompletionNotifyingBuildActionRunner.java:41)
	at org.gradle.launcher.exec.RootBuildLifecycleBuildActionExecutor.lambda$execute$0(RootBuildLifecycleBuildActionExecutor.java:40)
	at org.gradle.composite.internal.DefaultRootBuildState.run(DefaultRootBuildState.java:122)
	at org.gradle.launcher.exec.RootBuildLifecycleBuildActionExecutor.execute(RootBuildLifecycleBuildActionExecutor.java:40)
	at org.gradle.internal.buildtree.DefaultBuildTreeContext.execute(DefaultBuildTreeContext.java:40)
	at org.gradle.launcher.exec.BuildTreeLifecycleBuildActionExecutor.lambda$execute$0(BuildTreeLifecycleBuildActionExecutor.java:65)
	at org.gradle.internal.buildtree.BuildTreeState.run(BuildTreeState.java:53)
	at org.gradle.launcher.exec.BuildTreeLifecycleBuildActionExecutor.execute(BuildTreeLifecycleBuildActionExecutor.java:65)
	at org.gradle.launcher.exec.RunAsBuildOperationBuildActionExecutor$3.call(RunAsBuildOperationBuildActionExecutor.java:61)
	at org.gradle.launcher.exec.RunAsBuildOperationBuildActionExecutor$3.call(RunAsBuildOperationBuildActionExecutor.java:57)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:199)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:73)
	at org.gradle.launcher.exec.RunAsBuildOperationBuildActionExecutor.execute(RunAsBuildOperationBuildActionExecutor.java:57)
	at org.gradle.launcher.exec.RunAsWorkerThreadBuildActionExecutor.lambda$execute$0(RunAsWorkerThreadBuildActionExecutor.java:36)
	at org.gradle.internal.work.DefaultWorkerLeaseService.withLocks(DefaultWorkerLeaseService.java:249)
	at org.gradle.internal.work.DefaultWorkerLeaseService.runAsWorkerThread(DefaultWorkerLeaseService.java:109)
	at org.gradle.launcher.exec.RunAsWorkerThreadBuildActionExecutor.execute(RunAsWorkerThreadBuildActionExecutor.java:36)
	at org.gradle.tooling.internal.provider.continuous.ContinuousBuildActionExecutor.execute(ContinuousBuildActionExecutor.java:110)
	at org.gradle.tooling.internal.provider.SubscribableBuildActionExecutor.execute(SubscribableBuildActionExecutor.java:64)
	at org.gradle.internal.session.DefaultBuildSessionContext.execute(DefaultBuildSessionContext.java:46)
	at org.gradle.tooling.internal.provider.BuildSessionLifecycleBuildActionExecuter$ActionImpl.apply(BuildSessionLifecycleBuildActionExecuter.java:100)
	at org.gradle.tooling.internal.provider.BuildSessionLifecycleBuildActionExecuter$ActionImpl.apply(BuildSessionLifecycleBuildActionExecuter.java:88)
	at org.gradle.internal.session.BuildSessionState.run(BuildSessionState.java:69)
	at org.gradle.tooling.internal.provider.BuildSessionLifecycleBuildActionExecuter.execute(BuildSessionLifecycleBuildActionExecuter.java:62)
	at org.gradle.tooling.internal.provider.BuildSessionLifecycleBuildActionExecuter.execute(BuildSessionLifecycleBuildActionExecuter.java:41)
	at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:63)
	at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:31)
	at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:52)
	at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:40)
	at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:47)
	at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:31)
	at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:65)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:37)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
	at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:39)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
	at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:29)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
	at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:35)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.create(ForwardClientInput.java:78)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.create(ForwardClientInput.java:75)
	at org.gradle.util.internal.Swapper.swap(Swapper.java:38)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:75)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
	at org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogAndCheckHealth.java:55)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
	at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:63)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:37)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
	at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:84)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:37)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
	at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:52)
	at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:297)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.IllegalStateException: Projects must be configuring
Caused by: java.lang.IllegalStateException: Projects must be configuring

	at org.jetbrains.kotlin.gradle.targets.js.npm.resolver.KotlinRootNpmResolver.prepareInstallation$kotlin_gradle_plugin_common(KotlinRootNpmResolver.kt:249)
	at org.jetbrains.kotlin.gradle.targets.js.npm.KotlinNpmResolutionManager.prepareIfNeeded(KotlinNpmResolutionManager.kt:213)
	at org.jetbrains.kotlin.gradle.targets.js.npm.KotlinNpmResolutionManager.prepareIfNeeded$default(KotlinNpmResolutionManager.kt:187)
	at org.jetbrains.kotlin.gradle.targets.js.npm.KotlinNpmResolutionManager.installIfNeeded$kotlin_gradle_plugin_common(KotlinNpmResolutionManager.kt:168)
	at org.jetbrains.kotlin.gradle.targets.js.npm.KotlinNpmResolutionManager.installIfNeeded$kotlin_gradle_plugin_common$default(KotlinNpmResolutionManager.kt:154)
	at org.jetbrains.kotlin.gradle.targets.js.npm.KotlinNpmResolutionManager.getNpmDependencyResolvedCompilation$kotlin_gradle_plugin_common(KotlinNpmResolutionManager.kt:233)
	at org.jetbrains.kotlin.gradle.targets.js.npm.NpmDependency.resolveProject(NpmDependency.kt:86)
	at org.jetbrains.kotlin.gradle.targets.js.npm.NpmDependency.resolve(NpmDependency.kt:50)
	at org.jetbrains.kotlin.gradle.targets.js.npm.NpmDependency.getFiles(NpmDependency.kt:93)
	at org.gradle.api.internal.artifacts.ivyservice.moduleconverter.dependencies.DefaultLocalConfigurationMetadataBuilder$DefaultLocalFileDependencyMetadata.getFiles(DefaultLocalConfigurationMetadataBuilder.java:100)
	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.artifact.LocalFileDependencyBackedArtifactSet.visit(LocalFileDependencyBackedArtifactSet.java:103)
	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.artifact.ParallelResolveArtifactSet$VisitingSet$StartVisitAction.execute(ParallelResolveArtifactSet.java:95)
	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.artifact.ParallelResolveArtifactSet$VisitingSet$StartVisitAction.execute(ParallelResolveArtifactSet.java:72)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.executeInParallel(DefaultBuildOperationExecutor.java:136)
	... 166 more
```

**Comment by xuan-nguyen-swe** [comment]
Run task `rootPackageJson`, I get error `Could not resolve io.github.oshai:kotlin-logging-js:4.0.0-beta-21.`

Tried both below, same error.
`implementation("io.github.oshai:kotlin-logging:4.0.0-beta-21")`
`implementation("io.github.oshai:kotlin-logging-js:4.0.0-beta-21")`

**Comment by oshai** [comment]
Please try again, because I do see the version on maven, might be caching (of error) issue: https://repo1.maven.org/maven2/io/github/oshai/kotlin-logging-js/4.0.0-beta-21/

**Comment by xuan-nguyen-swe** [comment]
Not sure if it's related but I am using JS LEGACY mode because the new IR has performance issue.
Kotlin 1.7.22

Then I tried multiple options below.
Before each try, I deleted cache at "~\.gradle\caches\modules-2\files-2.1\io.github.oshai".

1. implementation("io.github.oshai:kotlin-logging:4.0.0-beta-20")

Download https://repo.maven.apache.org/maven2/io/github/oshai/kotlin-logging-js/4.0.0-beta-20/kotlin-logging-js-4.0.0-beta-20.jar, took 91 ms (16,67 kB)
Download https://repo.maven.apache.org/maven2/io/github/oshai/kotlin-logging-js/4.0.0-beta-20/kotlin-logging-js-4.0.0-beta-20-sources.jar, took 70 ms (13,78 kB)

This is the directory at ~\.gradle\caches\modules-2\files-2.1\io.github.oshai
[kotlin-logging-js.zip](https://github.com/oshai/kotlin-logging/files/10807942/kotlin-logging-js.zip)

2. implementation("io.github.oshai:kotlin-logging-js:4.0.0-beta-20")

Download https://repo.maven.apache.org/maven2/io/github/oshai/kotlin-logging-js/4.0.0-beta-20/kotlin-logging-js-4.0.0-beta-20.jar, took 83 ms (16,67 kB)
There are multiple versions of "kotlin" used in nodejs build: 1.7.22, 1.8.10. Only latest version will be used.
Download https://repo.maven.apache.org/maven2/io/github/oshai/kotlin-logging-js/4.0.0-beta-20/kotlin-logging-js-4.0.0-beta-20-sources.jar, took 79 ms (13,78 kB)

This is the directory at ~\.gradle\caches\modules-2\files-2.1\io.github.oshai
[kotlin-logging-js.zip](https://github.com/oshai/kotlin-logging/files/10808003/kotlin-logging-js.zip)

3. implementation("io.github.oshai:kotlin-logging:4.0.0-beta-21")

Download https://repo.maven.apache.org/maven2/io/github/oshai/kotlin-logging/4.0.0-beta-21/kotlin-logging-4.0.0-beta-21-sources.jar, took 180 ms (51,99 kB)
Download https://repo.maven.apache.org/maven2/io/github/oshai/kotlin-logging/4.0.0-beta-21/kotlin-logging-4.0.0-beta-21.jar, took 75 ms (19,43 kB)
Failed building KotlinMPPGradleModel
org.gradle.internal.operations.BuildOperationQueueFailure: There was a failure while populating the build operation queue: Projects must be configuring

This is the directory at ~\.gradle\caches\modules-2\files-2.1\io.github.oshai
[kotlin-logging.zip](https://github.com/oshai/kotlin-logging/files/10807974/kotlin-logging.zip)

4. implementation("io.github.oshai:kotlin-logging-js:4.0.0-beta-21")

Nothing is downloaded.

Failed building KotlinMPPGradleModel
org.gradle.internal.operations.BuildOperationQueueFailure: There was a failure while populating the build operation queue: Projects must be configuring

**Comment by oshai** [comment]
Probably related, as I changed to the new IR (there was a warning, BOTH is deprecated). I can change back if needed.

**Comment by xuan-nguyen-swe** [comment]
Please support both until the new IR is really the way to go.
Currently, it's not yet ready.
Please see https://youtrack.jetbrains.com/issue/KT-51712

**Comment by xuan-nguyen-swe** [comment]
Cool!, Thank you a lot!
Everything works now.
