### ISSUE TITLE
[crash]No interface method atLevel(Lorg/slf4j/event/Level;)

### ISSUE THREAD

**Issue by titanseason** [oshai/kotlin-logging#334]
crash in kotlin multiplatform application
```
java.lang.NoSuchMethodError: No interface method atLevel(Lorg/slf4j/event/Level;)Lorg/slf4j/spi/LoggingEventBuilder; in class Lorg/slf4j/Logger; or its super classes (declaration of 'org.slf4j.Logger' appears in /data/app/.../base.apk!classes15.dex)
                                                    	at io.github.oshai.kotlinlogging.slf4j.internal.LocationIgnorantKLogger.at(LocationIgnorantKLogger.kt:25)
                                                    	at io.github.oshai.kotlinlogging.KLogger$DefaultImpls.at$default(KLogger.kt:130)
                                                    	at io.github.oshai.kotlinlogging.KLogger$DefaultImpls.info(KLogger.kt:55)
                                                    	at io.github.oshai.kotlinlogging.slf4j.internal.Slf4jLogger.info(Slf4jLogger.kt:5)
```

dependencies:
```
implementation io.github.oshai:kotlin-logging:4.0.2
implementation org.slf4j:slf4j-api:1.7.36
implementation org.slf4j:slf4j-simple:1.7.36
```

**Comment by oshai** [comment]
I am looking into it.

**Comment by oshai** [comment]
I released now `5.0.0-beta-03`, please try it when available.

**Comment by oshai** [comment]
@titanseason - can you please try version 5.0.1 and report if the issue has been fixed?

**Comment by titanseason** [comment]
> @titanseason - can you please try version 5.0.1 and report if the issue has been fixed?

Yes, this issue has been fixed!
